config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :workouts, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    member do
      post 'toggle_favorite', to: "workouts#toggle_favorite"
    end
    resources :workout_exercises, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  end
  resources :completed_workouts, only: [:index, :new, :create, :show]
  get '/dashboard', to: 'pages#dashboard', as: 'dashboard'
  # get '/homepage', to: 'pages#homepage', as: 'homepage'
  # get '/workouts/:id/inprogress', to: 'pages#inprogress', as: 'inprogress'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/completed_workout.rb
class CompletedWorkout < ApplicationRecord
  belongs_to :workout
  belongs_to :user
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  has_many :workout_exercises
  has_one_attached :photo
end

app/models/favorite.rb
# frozen_string_literal: true

class Favorite < ApplicationRecord
  extend ActsAsFavoritor::FavoriteScopes

  belongs_to :favoritable, polymorphic: true
  belongs_to :favoritor, polymorphic: true

  def block!
    update!(blocked: true)
  end
end

app/models/favourite_workout.rb
class FavouriteWorkout < ApplicationRecord
  belongs_to :user
  belongs_to :workout
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :workouts
  has_many :completed_workouts
  has_many :favourite_workouts
  acts_as_favoritor
end

app/models/workout.rb
class Workout < ApplicationRecord
  has_many :completed_workouts, dependent: :destroy
  has_many :workout_exercises, dependent: :destroy
  belongs_to :user
  has_one_attached :photo
  acts_as_favoritable

  CATEGORY = ["Warmup", "Weights", "Cardio"]
  DIFFICULTY = ["1😴1", "2😀2", "3🥵3", "4🤮4", "5💀5"]
end

app/models/workout_exercise.rb
class WorkoutExercise < ApplicationRecord
  belongs_to :workout
  belongs_to :exercise
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/completed_workouts_controller.rb
class CompletedWorkoutsController < ApplicationController
  def index
    @completed_workouts = CompletedWorkout.where(user_id: current_user.id).to_a
    @workouts = @completed_workouts.map do |completed_workout|
      Workout.find(completed_workout.workout_id)
    end
  end

  def show
    @completed_workout = CompletedWorkout.find_by(id: params[:id])
    @workout = CompletedWorkout.find_by(@completedworkout.workout_id)
  end

  def new
    @completed_workout = CompletedWorkout.new
  end

  def create
    @workout = Workout.find(params[:format])
    @completed_workout = CompletedWorkout.create(workout_id: @workout.id, user_id: current_user.id)
    if @completed_workout.save
      redirect_to completed_workouts_path
    else
      raise
    end
  end

  private

  # params etc

end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :set_exercise, only: [:show]

  def index
    if params[:query].present?
      @exercises = Exercise.search_by_name_category_sport_and_difficulty(params[:query])
    else
      @exercises = Exercise.all
    end
  end

  def show
  end

  private

  def set_exercise
    @exercise = Exercise.find(params[:id])
  end

  def exercise_params
    params.require(:exercise).permit(:name, :category, :sport, :difficulty, :description, :muscle_group, :exercise_image)
  end
end

app/controllers/favourite_workouts_controller.rb
class FavouriteWorkoutsController < ApplicationController
  def create
    FavouriteWorkout.create(user_id: current_user, workout_id: Workout.find_by(id: params[:id]).id)
    #unsure how this will work with a button
  end

  def update
    @favourite_workout = FavouriteWorkout.find_by(workout_id: Workout.find_by(id: params[:id]).id)
    @favouriteworkout.favourite = @favourite_workout.favourite ? false : true
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @workouts = Workout.all
  end

  def dashboard
    @completed_workouts = CompletedWorkout.where(user_id: current_user.id).to_a
    @workouts = Workout.all
    @favorite_workouts = current_user.all_favorites
    # @workout = Workout.find(params[:workout_id])
  end
end

app/controllers/workout_exercises_controller.rb
class WorkoutExercisesController < ApplicationController
  before_action :set_workoutexercise, only: [:show, :update, :edit]

  def new
    @workout_exercise = WorkoutExercise.new
    @workout = Workout.find(params[:workout_id])
  end

  def create
    @workout_exercise = WorkoutExercise.new(workoutexercise_params)
    @workout = Workout.find(params[:workout_id])
    @workout_exercise.workout = @workout
    @exercise = Exercise.find(@workout_exercise.exercise_id)

    respond_to do |format|
      if @workout_exercise.save
        format.html { redirect_to edit_workout_path(@workout) }
        # format.js {
        #   return render partial: 'workouts/workout_exercise', locals: {workout_exercise: @workout_exercise, exercise: @exercise}
        # }
        format.json
        # render json: @workout_exercise
        # format.json
      end
    end

    # if @workout_exercise.save
    #   redirect_to workout_path(@workout), notice: 'Workout Exercise was successfully created.'
    # else
    #   render :new
    # end
  end

  def show
  end

  def edit
    @workout_exercise = WorkoutExercise.find(params[:id])
    @workout = Workout.find(params[:workout_id])
  end

  def update
    @workout = Workout.find(params[:workout_id])
    @workout_exercise.update(workoutexercise_params)
    if @workout_exercise.save
      redirect_to edit_workout_path(@workout), notice: 'Workout Exercise was successfully updated.'
    else
      render notice: 'Failed.'
    end
  end

  def destroy
    @workout = Workout.find(params[:workout_id])
    @workout_exercise = WorkoutExercise.find(params[:id])
    @workout_exercise.destroy
    redirect_to edit_workout_path(@workout)
  end

  private

  def set_workoutexercise
    @workout_exercise = WorkoutExercise.find(params[:id])
  end

  def workoutexercise_params
    params.require(:workout_exercise).permit(:exercise_id, :reps, :exercise_duration, :sets, :weight, :sets_rests, :image_url, :photo)
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :authenticate_user!, only: :toggle_favorite

  def toggle_favorite
    @workout = Workout.find_by(id: params[:id])
    current_user.favorited?(@workout) ? current_user.unfavorite(@workout) : current_user.favorite(@workout)
    respond_to do |format|
      format.js {}
    end
  end

  def index
    @workouts = Workout.all
  end

  def show
    @workout = Workout.find(params[:id])
  end

  def new
    @workout = Workout.new
  end

  def create
    @workout = Workout.new(workout_params)
    @user = current_user
    @workout.user = @user
    if @workout.save
      redirect_to workouts_path
    else
      render :new
    end
  end

  def edit
    @workout = Workout.find(params[:id])
    @workout_exercise = WorkoutExercise.new
  end

  def update
    @workout = Workout.find(params[:id])
    if @workout.update(workout_params)
      redirect_to @workout, notice: 'workout was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @workout = Workout.find(params[:id])
    @workout.destroy
    redirect_to workouts_path
  end

  private

  def workout_params
    params.require(:workout).permit(:id, :name, :category, :sport, :difficulty, :workout_duration, :equipment, :muscle_group, :description, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/completed_workouts/index.html.erb
<div class="">
  <h1 style="margin: 24px 0px;">My Workout History:</h1>
</div>

  <% if @completed_workouts.length == 0 %>
    <%= link_to workouts_path do %>
      <div class="ws-excercise-card-ph"><h3><strong>You haven't completed any yet!</strong></h3></div>
    <% end %>
  <%end%>

  <div class="co-cards-container">
      <% @completed_workouts.each do |completed_workout|%>
        <div class="co-cards">
            <div class="co-image">
              <% workout = Workout.find(completed_workout.workout_id) %>
                <% if workout.photo.attached? %>
                  <%= cl_image_tag(workout.photo.key) %>
                <% else %>
                  <%= image_tag("https://post.healthline.com/wp-content/uploads/2020/02/man-exercising-plank-push-up-1200x628-facebook.jpg") %>
                <% end %>
            </div>
            <div class="co-name">
              <h1><%= workout.name %></h1>
            </div>
          <div class ="co-date">
            <p>Completed on: <strong><%= completed_workout.created_at.strftime("%b %e, %l:%M %p") %></strong></p>
          </div>
          <div>
            <a href="" class="btn-primary">Add workout to Strava</a>
          </div>
        </div>
      <% end %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flexbox - Create your perfect workout routine, Whatever your sport.</title>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= favicon_link_tag asset_path('favicon.ico') %>
  </head>

  <body>
    <div class="navbar-div">
      <% unless action_name == 'home' %>
        <%= render 'pages/navbar' %>
      <% end %>
    </div>

    <div class="content-div">
      <%= yield %>
    </div>

    <div class="footer-div">
      <% unless action_name == 'home' %>
        <%= render 'pages/footer' %>
      <% end %>
    </div>


      <%= render 'shared/flashes' %>


  </body>
</html>

app/views/pages/_footer.html.erb
<div class="footer">
  <div class="footer-items">

    <div class="footer-item-contact">Contact us</div>

  </div>
  <% gh = ["https://github.com/TomJAllen", "https://github.com/bkit13", "https://github.com/LamoG6", "https://github.com/oliverbarnes1"] %>
  <% git = gh.sample %>

  <div class="footer-items">
  <%= link_to git , target: :_blank, id: "bolt" do %>
    <div class="copy">Web Design by B.O.L.T.<br>Flexbox |  © 2021</div>
  <% end %>
  </div>

  <div class="sm-bar">
  <%= link_to "https://i.kym-cdn.com/photos/images/facebook/001/361/242/82a.jpg", target: :_blank do %>
    <i class="fab fa-facebook-square"></i>
  <% end %>
  <%= link_to "https://filmdaily.co/wp-content/uploads/2021/03/instagram-lede-2-1300x1303.jpg", target: :_blank do %>
    <i class="fab fa-instagram-square"></i>
  <% end %>
  <%= link_to "https://github.com/oliverbarnes1/flexbox", target: :_blank do %>
    <i class="fab fa-github-square"></i>
  <% end %>
  </div>
</div>

<script>
  const gh = ["https://github.com/TomJAllen", "https://github.com/bkit13", "https://github.com/LamoG6", "https://github.com/oliverbarnes1"]
  const bolt = document.getElementById("bolt")
  bolt.addEventListener("click", ()=> {
    bolt.href = gh[Math.round((Math.random()*10)%3)]
  })
</script>

app/views/pages/_navbar.html.erb
<div class="navbar">
  <div class="navbar-items-left">
    <%= link_to dashboard_path, class: "navbar-brand" do %>
    <div>
      <%= image_tag "https://i.ibb.co/R9tqn5p/o-t.png" %>
    </div>
    <div>
      <h1 class="flexbox-heading">lexBox</h1>
    </div>
    <% end %>
  </div>
  <ul class="navbar-items-center">
    <%= link_to dashboard_path do %>
      <div class="navbar-item-center"><li class="navbar-item">Dashboard</li></div>
    <%end%>
    <%= link_to workouts_path do %>
      <div class="navbar-item-center"><li class="navbar-item">Workouts</li></div>
    <%end%>
    <%= link_to completed_workouts_path do %>
      <div class="navbar-item-center"><li class="navbar-item">History</li></div>
    <%end%>
  </ul>
  <div class ="navbar-items-right">
    <% if user_signed_in? %>
      <%# <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
      <%= link_to destroy_user_session_path, method: :delete do %>
        <p class="button-primary">Log Out</p>
      <% end %>
      <img src="https://st2.depositphotos.com/1006318/5909/v/950/depositphotos_59095055-stock-illustration-profile-icon-male-avatar.jpg" class="avatar-bordered">
    <% else %>
      <div class="navbar-item">
        <%# <%= link_to "Log in", new_user_session_path%>
        <%= link_to new_user_session_path do %>
          <p class="button-primary">Log In</p>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/_test_form.html.erb
<div class="form-div">
  <%= simple_form_for @workout, :html => { class: 'form' } do |f| %>
      <%= f.input :name, title: "name", input_html: { id: 'field'}%>
      <%= f.input :category, title: "category", input_html: { id: 'field'}%>
      <%= f.input :sport, title: "sport", input_html: { id: 'field'}%>
    <div class="submit-div">
      <%= f.submit "test!", class: "btn btn-primary form-button" %>
    </div>
  <%end%>
</div>

app/views/pages/dashboard.html.erb
<div class="dash-content-div-top">
  <% if user_signed_in? %>
    <h1>Hello, <%= current_user.email %>!</h1>
  <% else %>
    <h1>Hello!</h1>
  <% end %>
</div>
  <div class="dash-content-div">
    <div class="home-cards-container">
      <div class="nw-text-h1">
        <h5>MY WORKOUTS</h5>
      </div>
      <div class="fav-workouts-grid">
        <%= link_to workouts_path do %>
          <div class="card-add-new-workout-top-1">
              <h4>Find a<br> workout!</h4>
          </div>
        <% end %>
        <div class="lc-right-div">
          <h6 class="mini-title">Or create<br> one here:</h6>
          <%= link_to new_workout_path do %>
            <div class="card-add-new-workout-top">
              <h4>+</h4>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="home-cards-container-down">
      <div class="nw-text-h1">
        <h5>RECENT WORKOUTS</h5>
      </div>
      <% if @completed_workouts.length == 0 %>
      <%= link_to workouts_path do %>
        <div class="no-recent-workouts-grid">
          <div class="no-recent-workout-list-card-right">
            <h4 class="no-recents"> You have no recent workouts </h4>
          </div>
        </div>
      <% end %>
      <% end %>
      <div class="completed-cards-container">
        <% @completed_workouts.last(3).each do |completed_workout| %>
          <% workout = Workout.find(completed_workout.workout_id) %>
          <%= link_to completed_workouts_path do %>
            <div class="recent-workouts-grid">
              <div class="recent-workout-list-card-left">
                <% if workout.photo.attached? %>
                  <%= cl_image_tag(workout.photo.key) %>
                <% else %>
                  <%= image_tag("https://post.healthline.com/wp-content/uploads/2020/02/man-exercising-plank-push-up-1200x628-facebook.jpg") %>
                <% end %>
              </div>
                <div class="recent-workout-list-card-right">
                  <p class="dashboard-completed"><%= workout.name %></p>
                  <h3 class="dashboard-emoji"><%= workout.difficulty.slice!(1) %></h3>
                </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
<div class="dash-content-div-bottom">
  <div class="home-container-bottom">
    <div class="nw-text-h1">
      <h4>FAVOURITE WORKOUTS</h4>
    </div>
    <div class="fav-workouts-grid-down" >
      <% if @favorite_workouts.length == 0 %>
        <%= link_to workouts_path do %>
          <div class="card-no-workouts-down">
            <h4 class="favourites-btn">No Favourites 😢 <br> Add some? </h4>
          </div>
        <% end %>
      <% else %>
        <% @favorite_workouts.last(3).each do |fav| %>
          <% @workouts.each do |workout| %>
            <% if workout.id == fav.favoritable.id %>
              <div class="dashboard-link-container">
                <%= link_to workout_path(workout) do %>
                  <div class="workout-card">
                    <% if workout.photo.attached? %>
                      <%= cl_image_tag(workout.photo.key) %>
                    <% else %>
                      <%= image_tag("https://post.healthline.com/wp-content/uploads/2020/02/man-exercising-plank-push-up-1200x628-facebook.jpg") %>
                    <% end %>
                    <div class="workout-card-info">
                      <div>
                        <h1 class="workout-name"><%= workout.name %></h1>
                        <p class="workout-card-sport"><em>Sport:</em> <%= workout.sport %></p>
                        <p class="workout-card-category"><em><%= workout.category %></em></p>
                        <h3 class="workout-card-emoji"><%= workout.difficulty.slice!(1) %></h3>
                        <p class="workout-card-time"><strong>Time:</strong> <%= workout.workout_duration %> mins</p>
                      </div>
                    </div>
                  </div>
                <% end %>
              </div>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
      <% unless @favourite_workouts == nil%>
        <%= link_to workouts_path do %>
          <div class="card-all-workouts-down">
            <h2 class="favourites-btn">View Favourite Workouts</h2>
          </div>
        <%end%>
      <%end%>
    </div>
    </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="hp-background">
  <%# <div class="logo">
      <img src="app/assets/images/logo1.png">
  </div> %>

  <div class="hp-navbar">
    <% unless user_signed_in? %>
      <%= link_to new_user_session_path do %>
        <p class="button-primary">Login</p>
      <% end %>
      <%= link_to new_user_registration_path do %>
        <p class="button-secondary">Sign Up</p>
      <% end %>
    <% end %>
  </div>

  <div class="vid">
    <%= video_tag "workout.mp4", class:"vid-class", autoplay: :autoplay, loop: :loop, muted: :muted %>
  </div>

  <div class="hp-text">
      <div class="hp-text-logo">
        <img src="https://i.ibb.co/R9tqn5p/o-t.png" >
        <h1 style="font-size: 100px;"><strong>lexBox</strong></h1>
      </div>
      <p class="description-text">Whatever your sport, create your perfect workout routine.</p>
      <% if user_signed_in? %>
        <%= link_to dashboard_path do %>
          <p class="button-primary">Lets Go <i class="fas fa-arrow-right"></i></p>
        <% end %>
      <% else %>
        <%= link_to new_user_session_path do %>
          <p class="button-primary">Lets Go <i class="fas fa-arrow-right"></i></p>
        <% end %>
      <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/workout_exercises/edit.html.erb
<div class="nw-container">
  <div class="nw-title">
    <h2><strong>Edit exercise</strong></h2>
  </div>
    <%= simple_form_for [@workout, @workout_exercise], html: { class: "nw-form"} do |f|%>
      <%= f.input :reps, label: "Reps", :input_html => { class: 'field' } %>
      <%= f.input :sets, label: "Sets", :input_html => { class: 'field' } %>
      <%= f.input :weight, label: "Weight", :input_html => { class: 'field' } %>
      <%= f.input :exercise_duration, label: "Exercise duration (sec)", :input_html => { class: 'field' } %>
      <%= f.button :submit, "Save your changes",  class: "submit-button booking-submit"  %>
    <% end %>
  </div>

app/views/workout_exercises/new.html.erb
<div class="nwe-container">

  <div class="nwe-title">
    <h2><strong>Add a new exercise to your workout</strong></h2>
  </div>

  <div class="nwe-form-container">
    <h2>Exercise details</h2>
    <%= simple_form_for [@workout, @workout_exercise], html: { class: "nw-form"} do |f|%>
      <%= f.association :exercise, label: "Select exercise", :input_html => { class: 'field' } %>
      <%= f.input :reps, label: "Reps", :input_html => { class: 'field' } %>
      <%= f.input :sets, label: "Sets", collection: ["😴", "😀", "🥵", "🤮", "💀"], label: "Difficulty", :input_html => { class: 'field' } %>
      <%= f.input :weight, label: "Weight", :input_html => { class: 'field' } %>
      <%= f.input :exercise_duration, label: "Exercise duration", :input_html => { class: 'field' } %>
      <%= link_to "Cancel", edit_workout_path(@workout), class: "button-secondary" %>
      <%= f.button :submit, "Add exercise",   class: "button-primary"  %>
    <% end %>
  </div>
</div>

app/views/workouts/_workout_exercise.html.erb
  <div class="we-excercise-card">
    <div class="we-image-div">
      <%= cl_image_tag(exercise.photo.key) %>
    </div>

    <div class="we-exercise-name">
      <h3><strong><%= exercise.name %></strong></h3>
    </div>

    <%= exercise.difficulty %>


    <div class ="we-few-content-right">
      <%# <%= link_to "Edit",  edit_workout_workout_exercise_path(workout_exercise.workout_id, workout_exercise.id), class:"edit-icon"%>
        <div class="edit-button" id="<%= workout_exercise.id %>"><i class="fas fa-edit" style="margin: 10px;"></i></i></div>
        <%= link_to new_workout_path do %>
          <%= link_to "",  workout_workout_exercise_path(@workout.id, workout_exercise.id), method: :delete, class: "far fa-trash-alt", style: "margin: 10px;"%>
        <%end%>





        <%#= link_to "Delete",  workout_workout_exercise() , action: delete, class:"button-secondary"%>
    </div>
  </div>

app/views/workouts/index.html.erb
<div class=>
  <h1 style="margin: 24px 0px;">All Workouts:</h1>

  <div class="workout-card-index-div">
    <%= link_to new_workout_path do %>
      <div class="workout-card-info-index add-workout-button">
        <p class="add-workout-button-text">+</p>
      </div>
    <%end%>

    <% unless @workouts == []%>
      <% @workouts.reverse.each do |workout|%>
          <%= tag.div class: "workout-card-info-index", id: dom_id(workout) do %>
            <%= link_to toggle_favorite_workout_path(workout), remote: true, method: :post do %>
              <div class="favourite-icon-div">
                <div class="favourite-icon <%= 'active-icon' if current_user.favorited?(workout) %>" data-id="<%= workout.id %>">
                  <i class="fas fa-heart"></i>
                </div>
              </div>
            <% end %>
            <% if workout.photo.attached? %>
              <%= cl_image_tag(workout.photo.key) %>
            <% else %>
              <%= image_tag("https://post.healthline.com/wp-content/uploads/2020/02/man-exercising-plank-push-up-1200x628-facebook.jpg") %>
            <% end %>
            <%= link_to workout_path(workout) do %>

              <div class="workout-card-text">
                <h1 class="workout-name"><%= workout.name %></h1>
                <p class="workout-card-sport"><em>Sport:</em> <%= workout.sport %></p>
                <p class="workout-card-category"><em><%= workout.category %></em></p>
                <h3 class="workout-card-emoji" ><%= workout.difficulty.slice!(1) %></h3>
                <p class="workout-card-time"><strong>Time:</strong> <%= workout.workout_duration %> mins</p>
                <%= link_to workout_path(workout), method: :delete do %>
                  <div class="deleteboi"><i class="far fa-trash-alt" style="margin: 10px;"></i></div>
                <% end %>
              </div>
            <%end%>
          <% end %>
      <% end %>
    <% end%>

  </div>
</div>